[theme]
base="light"
primaryColor="#0F766E"
secondaryBackgroundColor="#F1F5F9"
textColor="#0F172A"
font="sans serif"

[server]
address = "127.0.0.1"
port = 8590
runOnSave = true

[browser]
gatherUsageStats = false

